points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      columns:
       pinky:
        key:
          col_net: P18
          splay: 15
        rows:
          bottom:
            bind: [5, 40, 0, 0]
          home:
          top:
       ring:
        key:
          spread: u+2
          splay: -10
          stagger: 17
          col_net: P15
        rows:
          bottom:
          home:
            bind: [0,0,0,0]
          top:
       middle:
        key:
          splay: -5
          spread: u+1
          stagger: 6
          col_net: P14
        rows:
          bottom:
            -bind: [0,3,10,3]
          home:
          top:
       index:
        key:
          splay: -5
          spread: u+1
          stagger: -5
          col_net: P16
        rows:
          bottom:
            -bind: [0,0,10,0]
          home:
          top:
       inner:
        key:
          spread: u
          stagger: -2
          col_net: P10
        rows:
          bottom:
            bind: [0,19,12,0]
          home:
            bind: [0,27,0,0]
          top:
      rows:
        bottom:
          padding: u
          row_net: P19
        home:
          padding: u
          row_net: P20
        top:
          row_net: P21
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift:
         - 0
         - -(u+3)
        rotate: -15
      columns:
        tuck:
          key:
            bind: [5,1,0,30]
            col_net: P19
        home:
          key:
            splay: -5
            spread: u+1
            stagger: -1
            bind: [0,1,0,3]
            col_net: P20
        reach:
          key:
            splay: -5
            spread: u+1
            stagger: -1
            bind: [1,0,0,15]
            col_net: P21
      rows:
        row:
          row_net: P9
        
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: u
      asym: left
      corner: 2
  fillet:
    - what: outline
      name: raw
      fillet: 2
pcbs:
  ferry:
    outlines:
      main:
        outline: fillet
    footprints:
      mx:
        what: mx
        where: "/^matrix_.*/"
        params:
          from: "{{colrow}}"
          to: "{{col_net}}"
          keycaps: true
          reverse: true
      diode:
        what: diode
        where: "/^matrix_.*/"
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mx_thumb:
        what: mx
        where: "/^thumb.*/"
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          keycaps: true
          reverse: true
      diode_thumb:
        what: diode
        where: "/^thumb.*/"
        params:
          from: "{{colrow}}"
          to: "{{col_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: down
        where:
          ref: matrix_inner_home
          shift: [19, -8.5]
          rotate: -90
      trrs:
        what: trrs
        where:
          ref: matrix_inner_home
          shift: [34.75, 6.5]
        params:
          A: GND
          B: GND
          C: P2
          D: VCC
          reverse: true
          symmetric: true
      # Mounting holes
      mount_top_left:
        what: mountinghole
        where:
          ref: matrix_pinky_top
          shift: [0.6u, 0]
      mount_bottom_left:
        what: mountinghole
        where:
          ref: matrix_pinky_bottom
          shift: [0.7u, 0.2u]
      mount_top_right:
        what: mountinghole
        where:
          ref: matrix_inner_top
          shift: [-0.5u, -0.3u]
      mount_bottom_right:
        what: mountinghole
        where:
          ref: thumb_reach_row
          shift: [-0.5u, 0.3u]